using System;

namespace Dapper.FluentMap.Mapping
{
    /// <summary>
    /// Describes how a mapped property participates in materialization and persistence operations.
    /// </summary>
    public sealed class PropertyPersistenceMetadata
    {
        /// <summary>
        /// Gets the default persistence metadata for a mapped property.
        /// </summary>
        public static readonly PropertyPersistenceMetadata Default =
            new PropertyPersistenceMetadata(
                participatesInMaterialization: true,
                participatesInInsert: true,
                participatesInUpdate: true,
                ignored: false,
                key: false,
                identity: false,
                generated: false,
                computed: false,
                databaseDefaultOnInsert: false);

        /// <summary>
        /// Gets the persistence metadata for a property ignored by FluentMap.
        /// </summary>
        public static readonly PropertyPersistenceMetadata Ignored =
            new PropertyPersistenceMetadata(
                participatesInMaterialization: false,
                participatesInInsert: false,
                participatesInUpdate: false,
                ignored: true,
                key: false,
                identity: false,
                generated: false,
                computed: false,
                databaseDefaultOnInsert: false);

        private PropertyPersistenceMetadata(
            bool participatesInMaterialization,
            bool participatesInInsert,
            bool participatesInUpdate,
            bool ignored,
            bool key,
            bool identity,
            bool generated,
            bool computed,
            bool databaseDefaultOnInsert)
        {
            if (ignored && (participatesInMaterialization || participatesInInsert || participatesInUpdate))
            {
                throw new ArgumentException("Ignored properties cannot participate in materialization, insert or update.");
            }

            if (ignored && (key || identity || generated || computed || databaseDefaultOnInsert))
            {
                throw new ArgumentException("Ignored properties cannot also be key, identity, generated, computed or database-default properties.");
            }

            if (computed && databaseDefaultOnInsert)
            {
                throw new ArgumentException("A property cannot be both computed and database-default-on-insert.");
            }

            if (computed && (participatesInInsert || participatesInUpdate))
            {
                throw new ArgumentException("Computed properties cannot participate in insert or update.");
            }

            if (computed && !generated)
            {
                throw new ArgumentException("Computed properties must be generated.");
            }

            if (identity && !generated)
            {
                throw new ArgumentException("Identity properties must be generated.");
            }

            if (identity && (participatesInInsert || participatesInUpdate))
            {
                throw new ArgumentException("Identity properties cannot participate in insert or update.");
            }

            ParticipatesInMaterialization = participatesInMaterialization;
            ParticipatesInInsert = participatesInInsert;
            ParticipatesInUpdate = participatesInUpdate;
            IgnoredByFluentMap = ignored;
            IsKey = key;
            IsIdentity = identity;
            IsGenerated = generated;
            IsComputed = computed;
            HasDatabaseDefaultOnInsert = databaseDefaultOnInsert;
        }

        /// <summary>
        /// Gets a value indicating whether this property participates in read materialization.
        /// </summary>
        public bool ParticipatesInMaterialization { get; }

        /// <summary>
        /// Gets a value indicating whether this property participates in generated INSERT commands.
        /// </summary>
        public bool ParticipatesInInsert { get; }

        /// <summary>
        /// Gets a value indicating whether this property participates in generated UPDATE commands.
        /// </summary>
        public bool ParticipatesInUpdate { get; }

        /// <summary>
        /// Gets a value indicating whether this property is ignored by FluentMap.
        /// </summary>
        public bool IgnoredByFluentMap { get; }

        /// <summary>
        /// Gets a value indicating whether this property identifies the row.
        /// </summary>
        public bool IsKey { get; }

        /// <summary>
        /// Gets a value indicating whether this property is an identity generated by the database.
        /// </summary>
        public bool IsIdentity { get; }

        /// <summary>
        /// Gets a value indicating whether this property can be generated by the database.
        /// </summary>
        public bool IsGenerated { get; }

        /// <summary>
        /// Gets a value indicating whether this property is computed by the database.
        /// </summary>
        public bool IsComputed { get; }

        /// <summary>
        /// Gets a value indicating whether the database supplies a default value when the column is omitted from INSERT.
        /// </summary>
        public bool HasDatabaseDefaultOnInsert { get; }

        internal PropertyPersistenceMetadata ExcludeFromInsert()
        {
            EnsureNotIgnored();

            if (IsIdentity)
            {
                return this;
            }

            return With(participatesInInsert: false);
        }

        internal PropertyPersistenceMetadata ExcludeFromUpdate()
        {
            EnsureNotIgnored();

            return With(participatesInUpdate: false);
        }

        internal PropertyPersistenceMetadata ReadOnly()
        {
            EnsureNotIgnored();

            return With(participatesInInsert: false, participatesInUpdate: false);
        }

        internal PropertyPersistenceMetadata Computed()
        {
            EnsureNotIgnored();
            EnsureNotKey(nameof(Computed));

            if (HasDatabaseDefaultOnInsert)
            {
                throw new FluentMapConfigurationException("A database-default property cannot also be configured as computed.");
            }

            return With(
                participatesInInsert: false,
                participatesInUpdate: false,
                generated: true,
                computed: true,
                databaseDefaultOnInsert: false);
        }

        internal PropertyPersistenceMetadata DatabaseDefaultOnInsert()
        {
            EnsureNotIgnored();

            if (IsComputed)
            {
                throw new FluentMapConfigurationException("A computed property cannot also be configured with a database default on insert.");
            }

            if (IsIdentity)
            {
                throw new FluentMapConfigurationException("An identity property cannot also be configured with a database default on insert.");
            }

            return With(
                participatesInInsert: false,
                generated: true,
                databaseDefaultOnInsert: true);
        }

        internal PropertyPersistenceMetadata Key()
        {
            EnsureNotIgnored();

            if (IsComputed)
            {
                throw new FluentMapConfigurationException("A computed property cannot also be configured as a key.");
            }

            return With(key: true, participatesInUpdate: false);
        }

        internal PropertyPersistenceMetadata Identity()
        {
            EnsureNotIgnored();

            if (IsComputed)
            {
                throw new FluentMapConfigurationException("A computed property cannot also be configured as an identity.");
            }

            if (HasDatabaseDefaultOnInsert)
            {
                throw new FluentMapConfigurationException("A database-default property cannot also be configured as an identity.");
            }

            return With(
                participatesInInsert: false,
                participatesInUpdate: false,
                key: true,
                identity: true,
                generated: true);
        }

        internal PropertyPersistenceMetadata GeneratedNone()
        {
            EnsureNotIgnored();

            return With(
                participatesInInsert: true,
                participatesInUpdate: !IsKey,
                identity: false,
                generated: false,
                computed: false,
                databaseDefaultOnInsert: false);
        }

        private void EnsureNotIgnored()
        {
            if (IgnoredByFluentMap)
            {
                throw new FluentMapConfigurationException("Ignored properties cannot be configured with persistence write semantics.");
            }
        }

        private void EnsureNotKey(string operation)
        {
            if (IsKey)
            {
                throw new FluentMapConfigurationException($"A key property cannot also be configured with {operation} persistence semantics.");
            }
        }

        private PropertyPersistenceMetadata With(
            bool? participatesInMaterialization = null,
            bool? participatesInInsert = null,
            bool? participatesInUpdate = null,
            bool? ignored = null,
            bool? key = null,
            bool? identity = null,
            bool? generated = null,
            bool? computed = null,
            bool? databaseDefaultOnInsert = null)
        {
            return new PropertyPersistenceMetadata(
                participatesInMaterialization ?? ParticipatesInMaterialization,
                participatesInInsert ?? ParticipatesInInsert,
                participatesInUpdate ?? ParticipatesInUpdate,
                ignored ?? IgnoredByFluentMap,
                key ?? IsKey,
                identity ?? IsIdentity,
                generated ?? IsGenerated,
                computed ?? IsComputed,
                databaseDefaultOnInsert ?? HasDatabaseDefaultOnInsert);
        }
    }

    /// <summary>
    /// Exposes persistence metadata for a property map without changing the original <see cref="IPropertyMap"/> contract.
    /// </summary>
    public interface IPropertyMapWithPersistenceMetadata
    {
        /// <summary>
        /// Gets the configured persistence metadata for the property.
        /// </summary>
        PropertyPersistenceMetadata Persistence { get; }
    }

    internal static class PropertyMapPersistence
    {
        internal static PropertyPersistenceMetadata GetPersistence(IPropertyMap propertyMap)
        {
            if (propertyMap == null)
            {
                throw new ArgumentNullException(nameof(propertyMap));
            }

            var mapWithPersistence = propertyMap as IPropertyMapWithPersistenceMetadata;
            if (mapWithPersistence != null)
            {
                return mapWithPersistence.Persistence;
            }

            return propertyMap.Ignored
                ? PropertyPersistenceMetadata.Ignored
                : PropertyPersistenceMetadata.Default;
        }
    }
}
